/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package demo

import codelabs.Repository

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main(args: Array<String>) {
    println(App().greeting)
    Repository.users
    println(Repository.users)
}
