/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package demo

import codelabs.Repository
import codelabs.User

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main(args: Array<String>) {
    var user =  User("Jane", "Doe")
    val user1=  User("Jane", "Doe")
    val user2 =  User("Jane", "Doe")

    user = User("John")

    //Igualdad Estructural
    val structurallyEqual =  user1 == user2
    val referentiallyEqual = user1 === user2

    println(App().greeting)
    println(structurallyEqual)
    println(referentiallyEqual)
    println(user.toString())

}
